# Generated by Django 4.0.6 on 2022-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_org', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('sum', models.FloatField()),
                ('service', models.CharField(max_length=100)),
            ],
        ),
    ]
